### ISSUE TITLE
Center blocks on index.php

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD150#2]
Hey,

I just want to know if the "center" blocks are supposed to be dsplayed anywhere but on `portal.php` page? That's the only place they appear right now

**Comment by vendethiel** [comment]
Well, I "fixed" it, but I have no idea how do you decide if a block should be forum-wide or not.

**Comment by MWE001** [comment]
It has been a bit since I have messed with it. What I need to do is do a install and have a go at it to remember it all. Life and health forced me to take a long break and I forgot more than I ever knew. I do have one install currently active that has major issues. The center blocks on the portal page will not display so I can't use it to try out. Ill give a quick install of this and let you know whats going on.

**Comment by vendethiel** [comment]
> The center blocks on the portal page will not display so I can't use it to try out.

I'll fix it for you if you can spot which block it is that's the issue :-)

**Comment by MWE001** [comment]
As far as the center blocks go, they will obviously not appear on the forum (index) BUT, if you create another new page in IM Portal, you can choose the layout. Choose 2 or 3 layout for a test. Now you go to blocks management and click on your new page you just created. When you add blocks, it will give you a choice of where you wnat that block placed. Tah dah! Center blocks will work. =)

**Comment by MWE001** [comment]
Ok I'll go have a look at it and see what one it is. I have to run and help the wife real quick, but will back in 30 or so.

**Comment by vendethiel** [comment]
> Tah dah! Center blocks will work. =)

Right. That was my question. If center blocks shouldn't appear on the forum index, I guessit works.

**Comment by MWE001** [comment]
Album block was bad on little elm is why it wouldnt work  lol now it all is working. Now I really got to run wife is giving me the evil eye. be back in a short.

**Comment by vendethiel** [comment]
Is the album block still broken after my fixes? I can take a look.
Most of the fixes are from Icy / will go to Icy anyway. Codebases are somewhat similar.

Obviously I hope you don't regret migrating to IP ;-).

**Comment by MWE001** [comment]
No, I dont regret at all. I really do like Icy. The admin panel took me a bit to get the swing of but now I make my way around it pretty well. Some of the code base I am still having issues with as it is is so different than what I am used to. I only messed with vanilla phpBB and / or Integarmod or IM Portal sites since 2004 or so. lol 

But as far as integra goes, Man so many good people worked on it and like Icy, I REALLY hate to see it go by the way side. So much work and effort. And comes along Facebook and ruins it all.

**Comment by MWE001** [comment]
Ill check album block here in a second or two. I just applied a few other fixes to the site. let me see what happens.

**Comment by MWE001** [comment]
Ok the album block now works. Now the issue is images. No thumbnails are there. if I go deep in to the album and click on the image name in blue, the full  size image will then show.

**Comment by MWE001** [comment]
> Well, I "fixed" it, but I have no idea how do you decide if a block should be forum-wide or not.

Actually a block would not be forum wide. How it works is when you create a cms page like we talked about a few comments back, it gives you the option of setting that page to forum wide blocks. If you set it to no, all you will have is a single column cms page. If you set it to yes, you can add left or right blocks or both.  

There is a couple more tricks that are coming back to me now as well like setting it so there is no blocks on the forum and it is 100% width of the page and so on. It is pretty versatile.

On a side note, the one thing Integra always needed is SQL optimization like Icy has. Integra is a great package but boy it sure loves it server resources. I got tagged by a host more than once but I shrugged it off.

**Comment by vendethiel** [comment]
> But as far as integra goes, Man so many good people worked on it and like Icy, I REALLY hate to see it go by the way side. So much work and effort. And comes along Facebook and ruins it all.

I really understand what you mean.

> Ok the album block now works. Now the issue is images. No thumbnails are there. if I go deep in to the album and click on the image name in blue, the full size image will then show.

Good for the block. I'll look at the thumbnails at some point.

> Actually a block would not be forum wide. How it works is when you create a cms page like we talked about a few comments back, it gives you the option of setting that page to forum wide blocks. If you set it to no, all you will have is a single column cms page. If you set it to yes, you can add left or right blocks or both.

So, can only one page be forum-wide blocks, or are the blocks "accumulated" from all the pages with "forum-wide" blocks option? How do you create a new CMS page just for content and link to it?

Even tho Icy CMS is based on IMPortal, I really think IP's version is superior. (Well, since it's been maintained...)

**Comment by vendethiel** [comment]
> On a side note, the one thing Integra always needed is SQL optimization like Icy has. Integra is a great package but boy it sure loves it server resources.

If you know of really bad ones I can take a look. But SQL optimizations are a bit too much time-intensive for me to fix...

**Comment by MWE001** [comment]
No, not only one page can be, many pages can be. As many pages as you feel like making. If you want forum wide blocks, you can do it. if not that is ok to. I do know a trick to make the forum have blocks as well. 

I do like IP IM Portal version. it is nice. It took me a good bit to figure it out. With Integras version, I knew right away how to use it. I think one is superior to the other and one might be a shade more user friendly. I think it is a matter of to each their own. The more I use IP version, the more I like it. That is way to much work for me to even think of trying  lol. Im lucky to fix a bug every now and again let alone develop software such as Integra or Icy. 

As far as the sql goes, I would need to have a good look at things and take notes. It has been a few years since I looked in to it. I lost all my notes I had. I did get IM 150 working tonight on a local host server. OUCH! It don't like WAMP. As far as my server space goes on my live server hosting package, I don't have near enough room to install it. yet. I might need to do some deleteing to try it out.

**Comment by vendethiel** [comment]
I'm going to close this one, since it appears to be fixed :).
